# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6a1d231c15634083008a291c15ba10f24c70cc91bad8c7f017989dd8b55eda40b72b967b73ab36a9aa9ffd7e0a648f5356a2a3d19fab3b87c57161ae9a1f595e

test:
  secret_key_base: 032e760070bec032b9359a120f099519c2a771e88b522414b66fca354ae5f2afc055633db51e87e1a5862c3625adae8687b629ab6973abe4201441383495b339

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
